### ISSUE TITLE
关于响应式编程

### ISSUE THREAD

**Issue by duckyling** [emac/emac.github.io#4]
你好，看了你写的响应式编程的文章，由于刚接触不太懂，所以有几个小问题想请教一下。
1，文章中提到的RP的缺点之一是某个线程卡住可能拖垮整个应用，那么通常如何应对这个问题？采用微服务的熔断机制？
2，RP通过线程复用来提高吞吐量，但如果也达到了处理的极限的话，后续的请求是被直接抛弃吗？
3，RP链式调用下的异常如何处理？也是用@ExceptionHandler、@ControllerAdvice来处理吗？不处理的话，调用者会收到状态500的response？

**Comment by emac** [comment]
目前我还没机会在真实项目中大规模使用RP，下面的回答受限于我目前对RP的理解：

A1. 理想情况下，对于一个RP应用，所有的操作应该都是不阻塞的，也即不存在线程卡住的可能。这个和node, redis的单线程设计是同样的道理。
A2. 至少有两种方式，一种是在接收端引入缓存，一种是在发送端支持背压。
A3. 这个没有研究过，可以查阅Spring官方文档。

**Comment by duckyling** [comment]
非常感谢！
